### ISSUE TITLE
Battery Status is not correct after update

### ISSUE THREAD

**Issue by sid684** [ioBroker/ioBroker.zigbee#1465] opened 2022-05-31 12:18 UTC
I´ve updated to IOBroker Adapter version 1.7.4. The battery status of all my Xiaomi Sensor devices (e.g. MotionSensor: https://www.zigbee2mqtt.io/devices/SNZB-03.html is not correct anymore. 
Every device have 100% .
![image](https://user-images.githubusercontent.com/96497597/171171235-5b765dea-0865-4c68-8a8c-0efee95752a2.png)
It works only in version 1.6.5.

**Comment by asgothian** [comment] 2022-06-01 05:07
Duplicate of #1454

**Closed by asgothian** 2022-06-01 05:07 UTC
