### ISSUE TITLE
Lidl HG06106A (Livarno Lux GU10 spot RGB) - color is wirteprotected

### ISSUE THREAD

**Issue by UweLoyal** [ioBroker/ioBroker.zigbee#1354] opened 2022-02-04 21:51 UTC
Lidl HG06106A (Livarno Lux GU10 spot RGB) is writeprodected.

{
  "type": "state",
  "common": {
    "name": "Color",
    "type": "string",
    "read": true,
    **"write": false**,
    "role": "level.color.rgb"
  },
  "native": {},
  "_id": "zigbee.0.588e81fffef66572.color",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1644007975662
}

Please correct this in definition file.

Rgds
    Uwe

**Comment by asgothian** [comment] 2022-02-05 08:17
- Which adapter version are you using ?
- What happens if you update to the adapter from latest or GitHub ?
A.

**Comment by UweLoyal** [comment] 2022-02-05 08:22
Version 1.6.6
It’s the newest Standard Version shown in ioBroker

Rgds
Uwe

Mit freundlichen Grüßen

Uwe Loyal
Am 5. Feb. 2022, 09:17 +0100 schrieb asgothian ***@***.***>:

**Comment by asgothian** [comment] 2022-02-05 08:24
This effect was caused by a bug present between 1.6.5 and 1.6.8 and is fixed in the current latest version (1.6.12)

**Closed by asgothian** 2022-02-05 08:24 UTC

**Comment by UweLoyal** [comment] 2022-02-05 13:33
Thanks, after update and restart the state for color (write=true) is now correct!

Rgds
Uwe
