### ISSUE TITLE
Please add support for Innr SP120 Smart Plug (already in zigbee2mqtt)

### ISSUE THREAD

**Issue by JinnBln** [ioBroker/ioBroker.zigbee#203] opened 2019-02-18 14:10 UTC
In Zigbee2MQTT wurde die Steckdose bereits aufgenommen.
The plug was already added in Zigbee2MQTT.

SP 120

switch:
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/<FRIENDLY_NAME>"
    availability_topic: "zigbee2mqtt/bridge/state"
    payload_off: "OFF"
    payload_on: "ON"
    value_template: "{{ value_json.state }}"
    command_topic: "zigbee2mqtt/<FRIENDLY_NAME>/set"

sensor:
  - platform: "mqtt"
    state_topic: "zigbee2mqtt/<FRIENDLY_NAME>"
    availability_topic: "zigbee2mqtt/bridge/state"
    unit_of_measurement: "Watt"
    icon: "mdi:flash"
    value_template: "{{ value_json.power }}"

**Comment by asgothian** [comment] 2019-02-20 13:55
Please provide information how the plug is identified when paired with the zigbee network. (best: screenshot from iobroker.zigbee with the tile showing the ? icon and plug address.

**Comment by asgothian** [comment] 2019-02-20 17:43
OK, i have a fork with a branch which has support for this plug. I need you to test it, though, as i cannot do so.

Please install the adapter (via GitHub icon) from 
https://github.com/asgothian/ioBroker.zigbee/tarball/InnrPlug. 
If it works, i'll submit a pull request to the main adapter

**Comment by JinnBln** [comment] 2019-02-20 20:09
My Adapter isn't working anymore.
![image](https://user-images.githubusercontent.com/47748074/53121160-d397a800-3553-11e9-8f20-df9e5b64ae40.png)

**Comment by asgothian** [comment] 2019-02-21 06:50
Does this error occur when you install the 0.9.1 version from the main repository as well ?

**Comment by JinnBln** [comment] 2019-02-21 07:14
No, after the error occured, I reinstalled the main repository and it works.

**Comment by asgothian** [comment] 2019-02-21 10:26
That is good news. Bad part is that i cannot debug this issue without hardware, as the adapter you installed runs just fine on my system without the plug.

**Comment by JinnBln** [comment] 2019-02-21 16:24
I've disconnected the Plug and your version is running fine.
If I try to pair the plug, the adapter crashes again.

**Comment by asgothian** [comment] 2019-02-21 17:35
That matches what i am seeing here. there is one more thing we can do to see if we can catch the cause, but that requires a bit more digging on the linux side. Can you see if you have a file called /var/log/syslog.log, and get that from your ioBroker system ? If so, i can patch the extended logging for the Zigbee backend back in and update the adapter version. Once installed, you can run it once with the plug connected and send me the file - perhaps that will tell me why it crashes.

Is that something you can / are willing to do ?

**Comment by JinnBln** [comment] 2019-02-22 06:14
yes i will^^ and i'm able to do this. The file is in place. Please patch the adapter version and I will send you the log file.

**Comment by asgothian** [comment] 2019-02-22 14:49
OK.. seems the patch is already in the branch. Please install the adapter, start it and post the syslog.log file.

A.

**Comment by asgothian** [comment] 2019-02-22 17:16
I may to have fount half the cause for the crash. Please update from GitHub and see if it still dies.

**Comment by JinnBln** [comment] 2019-02-22 20:31
![image](https://user-images.githubusercontent.com/47748074/53269449-2f476a00-36e9-11e9-9abd-4ca7e491247f.png)
![image](https://user-images.githubusercontent.com/47748074/53269467-3c645900-36e9-11e9-93df-3f9753e8faa7.png)

**Comment by JinnBln** [comment] 2019-02-22 20:33
Objects were created, but they don't work.

**Comment by asgothian** [comment] 2019-02-22 21:24
But it no longer crashes ?

**Comment by JinnBln** [comment] 2019-02-22 21:24
After a long time the objects now work. A restart of the adapter works too.
![image](https://user-images.githubusercontent.com/47748074/53272082-94eb2480-36f0-11e9-971b-3f30c98389bf.png)

Thank you.

**Comment by asgothian** [comment] 2019-02-22 21:31
ok.. so the plug works, but does not report power consumption.. that's half a win :)

**Comment by JinnBln** [comment] 2019-02-22 21:49
Thats right ;) Would you like to implement the power consumption too?

**Comment by asgothian** [comment] 2019-02-22 22:27
Yes, but that is currently blocked by a bug which causes the adapter to crash. I have an idea how to circumvent it, but i am not 100% certain that it will be effective.
(this also affects other plugs with power measurement, but not all)

**Comment by asgothian** [comment] 2019-02-24 17:33
I think i found the bug. Please install the repository from 
https://github.com/asgothian/ioBroker.zigbee/tarball/InnrPlug
and check if it runs. It should also provide power metering.

**Comment by JinnBln** [comment] 2019-02-24 18:40
I've installed your new repo. Now the plug has an icon, but there are no new objects.
![image](https://user-images.githubusercontent.com/47748074/53303533-013e6300-386c-11e9-82ae-73efc2e62cff.png)

**Comment by asgothian** [comment] 2019-02-24 18:55
did you upload the adapter ?

**Comment by JinnBln** [comment] 2019-02-24 19:09
no^^ now it works. Very nice. Thank you.
![image](https://user-images.githubusercontent.com/47748074/53303890-07364300-3870-11e9-83ea-30146c6824a6.png)

**Comment by asgothian** [comment] 2019-02-24 19:26
perfect.. can you please close this issue ?

**Closed** 2019-02-24 19:26 UTC
