### ISSUE TITLE
livarno led smart light bar not working

### ISSUE THREAD

**Issue by 2Moon4** [ioBroker/ioBroker.zigbee#1420] opened 2022-04-19 16:21 UTC
Hello,

(this is my first issue on github - so let me know if i missed something and perhaps need more information.)

I have a new device - but it will not work:
https://www.zigbee2mqtt.io/devices/14149505L_14149506L.html

The zigbee Interview is successful and objects in the zigbee-adapter tree appear.
![Screenshot 2022-04-19 181840](https://user-images.githubusercontent.com/103438374/164049615-24ade0bb-05ad-4194-ad54-3c836f88fe57.jpg)

![Screenshot 2022-04-19 180819](https://user-images.githubusercontent.com/103438374/164047739-3e1d1233-67de-46a7-b0e0-1f18a4faecfd.jpg)

(The values in these objects was set manually from me.)

The link_quality object is set properly - weired. So this is working. But nothing else. No changes at any object i made go to the device.
I tryed to "reconfigure" the device within the zigbee-adapter. But there was an error i don't understand.

----------

2022-04-19 17:30:33.418  - [32minfo[39m: zigbee.0 (1022) Zigbee: allowing new devices to join.
2022-04-19 17:31:09.501  - [32minfo[39m: zigbee.0 (1022) Starting interview of '0xb4e3f9fffee55df9'
2022-04-19 17:31:09.657  - [33mwarn[39m: zigbee.0 (1022) Device '0xb4e3f9fffee55df9' announced itself
2022-04-19 17:31:09.755  - [33mwarn[39m: zigbee.0 (1022) Object b4e3f9fffee55df9.effect is invalid: obj.common.states has an invalid type! Expected "object", received "string"
2022-04-19 17:31:09.756  - [33mwarn[39m: zigbee.0 (1022) This object will not be created in future versions. Please report this to the developer.
2022-04-19 17:31:09.794  - [33mwarn[39m: zigbee.0 (1022) Object zigbee.0.b4e3f9fffee55df9.effect is invalid: obj.common.states has an invalid type! Expected "object", received "string"
2022-04-19 17:31:09.795  - [33mwarn[39m: zigbee.0 (1022) This object will not be created in future versions. Please report this to the developer.
2022-04-19 17:31:10.950  - [32minfo[39m: zigbee.0 (1022) Successfully interviewed '0xb4e3f9fffee55df9', device has succesfully been paired
2022-04-19 17:34:44.778  - [32minfo[39m: zigbee.0 (1022) Zigbee: stop joining
2022-04-19 17:36:43.873  - [32minfo[39m: zigbee.0 (1022) Configuring 0xb4e3f9fffee55df9 TS0505B
2022-04-19 17:36:43.883  - [31merror[39m: zigbee.0 (1022) Reconfigure failed 0xb4e3f9fffee55df9 TS0505B, (TypeError: Cannot read property 'configure' of null
    at DeviceConfigure.doConfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js:145:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Promise.all (index 0)
    at Commands.reconfigure (/opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js:483:21))
2022-04-19 17:43:20.860  - [33mwarn[39m: zigbee.0 (1022) DeviceAvailability:Stopping to ping 0xb4e3f9fffee55df9 TS0505B after 11 ping attempts

---------------
My system configuration is:
raspberry pi 4
CC2652P2 Zigbee controller

![Screenshot 2022-04-19 181756](https://user-images.githubusercontent.com/103438374/164049481-f7e61bbf-e732-406d-925f-bf5b40682ce1.jpg)

raspberrypi Infos:

Plattform
    linux
Betriebssystem
    linux
Architektur
    arm
CPUs
    4
Geschwindigkeit
    1500 MHz
Modell
    ARMv7 Processor rev 3 (v7l)
RAM
    1.83 GB
System-Betriebszeit
    8 T. 03:48:12
Node.js
    v14.19.0 (Es gibt eine neuere Version: v14.19.1)
time
    1650385365926
timeOffset
    -120
Anzahl der Adapter
    406
NPM
    6.14.16
Datenträgergröße
    29.07 GB
freier Festplattenspeicher
    22.97 GB
Betriebszeit
    8 T. 03:48:06
Aktive Instanzen
    13
location
    /opt/iobroker/

**Comment by asgothian** [comment] 2022-04-19 19:13
which adapter version do you have installed ?

**Comment by asgothian** [comment] 2022-04-19 19:43
Duplicate of #1414

**Comment by 2Moon4** [comment] 2022-04-19 20:59
Thank you for your update!
This is sad: i REALLY searched for such issue - but i haven't found anything. 
Sorry for the inconvinience.

**Comment by asgothian** [comment] 2022-04-19 21:36
You did not answer the question.
The device should be supported with the correct adapter version - the data you posted indicates that it is not in yours.

**Comment by 2Moon4** [comment] 2022-04-20 07:41
Hello,

the adapter version is: v1.6.16

**Comment by asgothian** [comment] 2022-04-20 15:15
You can attempt to install the 1.6.17 from GitHub without removing and repairing the device. There is a good chance that it will be supported as Arteck updated support for a new version of the zigbee-herdsman-converters.

**Comment by 2Moon4** [comment] 2022-04-21 07:27
Ok - i will try to do so in the next days. Before this change i want to do a complete backup.

**Comment by 2Moon4** [comment] 2022-06-06 09:45
Hi,

with the new Zigbee Version 1.7.5. the smart LED Light Bar works!
Thank you!

**Closed** 2023-02-21 06:14 UTC
Labels: duplicate, Zigbee-Herdsman-Converters issue, TuYa
