### ISSUE TITLE
Error loading settings

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.zigbee#1098] opened 2021-05-14 11:37 UTC
I assume this has something to do with the new admin:

![grafik](https://user-images.githubusercontent.com/4311558/118265488-8c41bd00-b4b9-11eb-8275-75b656ab7980.png)

**Comment by di3t0** [comment] 2021-05-15 12:36
I have the same problem after updating to the new admin

**Comment by daniel-lo** [comment] 2021-05-16 15:05
Seems to be fixed in Admin v5.0.26

**Comment by asgothian** [comment] 2021-05-17 07:17
Duplicate of #1100

**Closed** 2021-05-31 10:57 UTC
Labels: duplicate
