### ISSUE TITLE
v1.4.4 - missing catch block with async function

### ISSUE THREAD

**Issue by quotschmacher** [ioBroker/ioBroker.zigbee#1011] opened 2021-02-22 07:35 UTC
first recognized this error in v1.4.5, switched back to v1.4.4 but the error still remains. it does not throw at the adapter start. the adapter is running fine and working and then suddenly the exception is soming.

i got 2 instances of the zigbee adapter - one with a raspbee ii and one with a ti board - the error only comes with the raspbee.

![fehler_1 4 5](https://user-images.githubusercontent.com/50583947/108676484-94a4e000-74e8-11eb-8f98-231667daa6e5.jpg)

**Comment by asgothian** [comment] 2021-02-22 08:02
the Screenshot is unusable for finding the error.

- post logs as Text, not Screenshot
- Post copied from the log file, not copied from the admin log page
- post log entries in code tag (<>)
- Post more information.

A.

**Comment by quotschmacher** [comment] 2021-02-22 08:14
`script.js.Lichtsteuerung.Kueche.kuechenbeleuchtung` is controlling devices with zigbee.0 -  so i would say there is no real connection between the script and the adapter crash. 
i left some startup infos for more details. do you need any more?

`2021-02-22 08:12:22.996  - info: javascript.0 (27856) script.js.Lichtsteuerung.Kueche.kuechenbeleuchtung: Kuechenlicht an
2021-02-22 08:21:27.861  - info: javascript.0 (27856) script.js.Lichtsteuerung.Kueche.kuechenbeleuchtung: Kuechenlicht dimmen
2021-02-22 08:22:33.357  - info: javascript.0 (27856) script.js.Lichtsteuerung.Kueche.kuechenbeleuchtung: Kuechenlicht an
2021-02-22 08:22:57.663  - warn: zigbee.0 (15747) Device '0x7cb03eaa00ad827e' announced itself
2021-02-22 08:23:10.290  - error: zigbee.0 (15747) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-02-22 08:23:10.291  - error: zigbee.0 (15747) unhandled promise rejection: undefined
2021-02-22 08:23:10.294  - info: zigbee.0 (15747) cleaned everything up...
2021-02-22 08:23:10.299  - info: zigbee.0 (15747) Zigbee: disabling joining new devices.
2021-02-22 08:23:10.801  - info: zigbee.0 (15747) terminating
2021-02-22 08:23:10.803  - warn: zigbee.0 (15747) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-02-22 08:23:11.536  - error: host.IoBrokerPi3 instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-02-22 08:23:11.544  - info: host.IoBrokerPi3 Restart adapter system.adapter.zigbee.0 because enabled
2021-02-22 08:23:41.612  - info: host.IoBrokerPi3 instance system.adapter.zigbee.0 started with pid 24693
2021-02-22 08:23:46.383  - info: zigbee.0 (24693) starting. Version 1.4.4 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.18.3, js-controller: 3.2.16
2021-02-22 08:23:46.575  - info: zigbee.0 (24693) Starting Zigbee  npm ...
2021-02-22 08:23:47.650  - info: zigbee.0 (24693) Installed Version: undefined
2021-02-22 08:23:47.717  - info: zigbee.0 (24693) Coordinator firmware version: {"type":"ConBee2/RaspBee2","meta":{"transportrev":0,"product":0,"majorrel":38,"minorrel":97,"maintrel":0,"revision":"0x26610700"}}
2021-02-22 08:23:47.770  - info: zigbee.0 (24693) Unable to disable LED, unsupported function.
2021-02-22 08:23:47.776  - info: zigbee.0 (24693)   --> transmitPower : normal
2021-02-22 08:23:47.779  - info: zigbee.0 (24693) Unable to set transmit power, unsupported function.
2021-02-22 08:23:47.790  - info: zigbee.0 (24693) Currently 19 devices are joined:`

**Comment by asgothian** [comment] 2021-02-22 09:19
Can you run the Adapter in debug ? Getting no stack trace makes the error hard to find. I doubt it is connected to any of the messages before, including the device announcement.

A.

**Comment by quotschmacher** [comment] 2021-02-22 09:52
just had this (only took log messages that had a similar timestamp)

```2021-02-22 10:42:10.576  - debug: zigbee.0 (26051) Non-pingable device 0xd0cf5efffe7b93a0 TRADFRI wireless dimmer was last seen '17800854.806' seconds ago.
2021-02-22 10:42:10.605  - debug: zigbee.0 (26051) Non-pingable device 0xec1bbdfffe9c3336 TRADFRI on/off switch was last seen '13534.925' seconds ago.
2021-02-22 10:42:10.613  - debug: zigbee.0 (26051) Non-pingable device 0xec1bbdfffea09292 TRADFRI on/off switch was last seen '14984.888' seconds ago.
2021-02-22 10:42:10.631  - debug: zigbee.0 (26051) Non-pingable device 0x90fd9ffffe08d5c6 TRADFRI remote control was last seen '1362267.524' seconds ago.
2021-02-22 10:42:10.635  - debug: zigbee.0 (26051) Non-pingable device 0x000d6f000f5e0d70 Motion Sensor-A was last seen '718159.768' seconds ago.
2021-02-22 10:42:10.638  - debug: zigbee.0 (26051) Non-pingable device 0x00158d0003416e98 ZBT-Remote-ALL-RGBW was last seen '4829255.09' seconds ago.
2021-02-22 10:42:10.731  - debug: zigbee.0 (26051) handleMessage. {"type":"readResponse","device":{"ID":19,"_type":"Router","_ieeeAddr":"0x842e14fffe139290","_networkAddress":48583,"_manufacturerID":4098,"_endpoints":[{"ID":1,"profileID":260,"deviceID":81,"inputClusters":[0,4,5,6,1794,2820],"outputClusters":[25,10],"deviceNetworkAddress":48583,"deviceIeeeAddress":"0x842e14fffe139290","clusters":{"genBasic":{"attributes":{"modelId":"TS0121","manufacturerName":"_TZ3000_g5xawfcq","powerSource":1,"zclVersion":3,"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"32770":2,"onOff":0,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":1}},"seMetering":{"attributes":{"currentSummDelivered":[0,1379],"divisor":100,"multiplier":1}},"haElectricalMeasurement":{"attributes":{"rmsVoltage":230,"rmsCurrent":0,"activePower":0,"acVoltageMultiplier":1,"acVoltageDivisor":1,"acCurrentMultiplier":1,"acCurrentDivisor":1000,"acPowerMultiplier":1,"acPowerDivisor":1}}},"_binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00212effff05ba42","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00212effff05ba42","endpointID":1}],"_configuredReportings":[],"meta":{}}],"_manufacturerName":"_TZ3000_g5xawfcq","_powerSource":"Mains (single phase)","_modelID":"TS0121","_applicationVersion":65,"_stackVersion":0,"_zclVersion":3,"_hardwareVersion":1,"_dateCode":"","_interviewCompleted":true,"_interviewing":false,"_skipDefaultResponse":false,"meta":{"configured":1},"_lastSeen":1613986930728,"_linkquality":124},"endpoint":"[Circular]","data":{"rmsVoltage":230,"rmsCurrent":0,"activePower":0},"linkquality":124,"groupID":null,"cluster":"haElectricalMeasurement","meta":{"zclTransactionSequenceNumber":81,"manufacturerCode":null,"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":true,"reservedBits":0}}}
2021-02-22 10:42:10.735  - debug: zigbee.0 (26051) Received Zigbee message from '0x842e14fffe139290', type 'readResponse', cluster 'haElectricalMeasurement', data '{"rmsVoltage":230,"rmsCurrent":0,"activePower":0}' from endpoint 1 with groupID null
2021-02-22 10:42:10.739  - debug: zigbee.0 (26051) Type readResponse device {"type":"device","device":{"ID":19,"_type":"Router","_ieeeAddr":"0x842e14fffe139290","_networkAddress":48583,"_manufacturerID":4098,"_endpoints":[{"ID":1,"profileID":260,"deviceID":81,"inputClusters":[0,4,5,6,1794,2820],"outputClusters":[25,10],"deviceNetworkAddress":48583,"deviceIeeeAddress":"0x842e14fffe139290","clusters":{"genBasic":{"attributes":{"modelId":"TS0121","manufacturerName":"_TZ3000_g5xawfcq","powerSource":1,"zclVersion":3,"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"32770":2,"onOff":0,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":1}},"seMetering":{"attributes":{"currentSummDelivered":[0,1379],"divisor":100,"multiplier":1}},"haElectricalMeasurement":{"attributes":{"rmsVoltage":230,"rmsCurrent":0,"activePower":0,"acVoltageMultiplier":1,"acVoltageDivisor":1,"acCurrentMultiplier":1,"acCurrentDivisor":1000,"acPowerMultiplier":1,"acPowerDivisor":1}}},"_binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00212effff05ba42","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00212effff05ba42","endpointID":1}],"_configuredReportings":[],"meta":{}}],"_manufacturerName":"_TZ3000_g5xawfcq","_powerSource":"Mains (single phase)","_modelID":"TS0121","_applicationVersion":65,"_stackVersion":0,"_zclVersion":3,"_hardwareVersion":1,"_dateCode":"","_interviewCompleted":true,"_interviewing":false,"_skipDefaultResponse":false,"meta":{"configured":1},"_lastSeen":1613986930728,"_linkquality":124},"mapped":{"zigbeeModel":["TS0121"],"model":"TS0121_plug","description":"10A UK or 16A EU smart plug","whiteLabel":[{"vendor":"BlitzWolf","model":"BW-SHP13"}],"vendor":"TuYa","fromZigbee":[{"cluster":"genOnOff","type":["attributeReport","readResponse"]},{"cluster":"haElectricalMeasurement","type":["attributeReport","readResponse"]},{"cluster":"seMetering","type":["attributeReport","readResponse"]},{"cluster":"genBasic","type":["attributeReport","readResponse"]},{"cluster":"genOnOff","type":["attributeReport","readResponse"]}],"toZigbee":[{"key":["state"]},{"key":["power_outage_memory"]},{"key":["scene_store"]},{"key":["scene_recall"]},{"key":["scene_add"]},{"key":["scene_remove"]},{"key":["scene_remove_all"]}],"meta":{"configureKey":1},"exposes":[{"type":"switch","features":[{"type":"binary","name":"state","property":"state","access":7,"value_on":"ON","value_off":"OFF","description":"On/off state of the switch","value_toggle":"TOGGLE"}]},{"type":"numeric","name":"power","property":"power","access":1,"unit":"W","description":"Instantaneous measured power"},{"type":"numeric","name":"current","property":"current","access":1,"unit":"A","description":"Instantaneous measured electrical current"},{"type":"numeric","name":"voltage","property":"voltage","access":1,"unit":"V","description":"Measured electrical potential value"},{"type":"numeric","name":"energy","property":"energy","access":1,"unit":"kWh","description":"Sum of consumed energy"},{"type":"enum","name":"power_outage_memory","property":"power_outage_memory","access":3,"values":["on","off","restore"],"description":"Recover state after power outage"},{"type":"numeric","name":"linkquality","property":"linkquality","access":1,"unit":"lqi","description":"Link quality (signal strength)","value_min":0,"value_max":255}]},"name":"0x842e14fffe139290"} incoming event: {"type":"readResponse","device":{"ID":19,"_type":"Router","_ieeeAddr":"0x842e14fffe139290","_networkAddress":48583,"_manufacturerID":4098,"_endpoints":[{"ID":1,"profileID":260,"deviceID":81,"inputClusters":[0,4,5,6,1794,2820],"outputClusters":[25,10],"deviceNetworkAddress":48583,"deviceIeeeAddress":"0x842e14fffe139290","clusters":{"genBasic":{"attributes":{"modelId":"TS0121","manufacturerName":"_TZ3000_g5xawfcq","powerSource":1,"zclVersion":3,"appVersion":65,"stackVersion":0,"hwVersion":1,"dateCode":""}},"genOnOff":{"attributes":{"32770":2,"onOff":0,"onTime":0,"offWaitTime":0,"tuyaBacklightMode":1}},"seMetering":{"attributes":{"currentSummDelivered":[0,1379],"divisor":100,"multiplier":1}},"haElectricalMeasurement":{"attributes":{"rmsVoltage":230,"rmsCurrent":0,"activePower":0,"acVoltageMultiplier":1,"acVoltageDivisor":1,"acCurrentMultiplier":1,"acCurrentDivisor":1000,"acPowerMultiplier":1,"acPowerDivisor":1}}},"_binds":[{"cluster":6,"type":"endpoint","deviceIeeeAddress":"0x00212effff05ba42","endpointID":1},{"cluster":2820,"type":"endpoint","deviceIeeeAddress":"0x00212effff05ba42","endpointID":1}],"_configuredReportings":[],"meta":{}}],"_manufacturerName":"_TZ3000_g5xawfcq","_powerSource":"Mains (single phase)","_modelID":"TS0121","_applicationVersion":65,"_stackVersion":0,"_zclVersion":3,"_hardwareVersion":1,"_dateCode":"","_interviewCompleted":true,"_interviewing":false,"_skipDefaultResponse":false,"meta":{"configured":1},"_lastSeen":1613986930728,"_linkquality":124},"endpoint":"[Circular]","data":{"rmsVoltage":230,"rmsCurrent":0,"activePower":0},"linkquality":124,"groupID":null,"cluster":"haElectricalMeasurement","meta":{"zclTransactionSequenceNumber":81,"manufacturerCode":null,"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":true,"reservedBits":0}}}
2021-02-22 10:42:10.746  - error: zigbee.0 (26051) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-02-22 10:42:10.747  - error: zigbee.0 (26051) unhandled promise rejection: undefined
2021-02-22 10:42:10.749  - info: zigbee.0 (26051) cleaned everything up...
2021-02-22 10:42:10.753  - info: zigbee.0 (26051) Zigbee: disabling joining new devices.```

**Comment by asgothian** [comment] 2021-02-22 10:32
Still nothing with any usable info. I am afraid I need to ask you to enable zigbee-herdsman-debug-info and debug mode and check again.

A.

**Comment by arteck** [comment] 2021-02-22 12:34
plz restart the PI

**Comment by quotschmacher** [comment] 2021-02-23 06:22
@arteck i restarted the pi

maybe this helps
```2021-02-23 06:12:05.237  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 183
2021-02-23 06:12:05.238  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:frameParser DATA_CONFIRM RESPONSE - destAddr: 0xbdc7 request id: 147 confirm status: 0
2021-02-23 06:12:05.239  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1
2021-02-23 06:12:05.239  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:adapter sendZclFrameToEndpoint - message send with transSeq Nr.: 132
2021-02-23 06:12:05.239  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver query aps data indication
2021-02-23 06:12:05.242  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 184
2021-02-23 06:12:05.244  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:adapter sendZclFrameToEndpoint ERROR: [object Object]
2021-02-23 06:12:05.247  - error: zigbee.0 (3198) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-02-23 06:12:05.247  - error: zigbee.0 (3198) unhandled promise rejection: undefined```

**Comment by asgothian** [comment] 2021-02-23 11:02
Can you post what happens in the 2 seconds before the first message ? Unfortunately, finding the initial rejection does not help with finding the missing catch. I am almost certain that this is the root cause, though.

Alternatively, can you patch the file zigbee-herdsman/src/adapter/deconz/adapter/deconzAdapter.ts, line 610 from 
```
debug(`sendZclFrameToEndpoint ERROR: ${error}`);
```
 to
```
debug(`sendZclFrameToEndpoint ERROR: ${JSON.stringify(error)}`);
```
and restart the adapter ?

**Comment by quotschmacher** [comment] 2021-02-23 11:09
here are some seconds of output before the error:

```2021-02-23 06:11:29.892  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:frameParser DATA_INDICATION RESPONSE - seqNr. 172 srcAddr: 0x787 destAddr: 0x0 profile id: 0x104 cluster id: 0x402
2021-02-23 06:11:29.893  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:frameParser response payload: 24,57,10,0,0,41,60,8
2021-02-23 06:11:29.895  - debug: zigbee.0 (3198) zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":true,"reservedBits":0},"transactionSequenceNumber":57,"manufacturerCode":null,"commandIdentifier":10},"Payload":[{"attrId":0,"dataType":41,"attrData":2108}],"Command":{"ID":10,"name":"report","parameters":[{"name":"attrId","type":33},{"name":"dataType","type":32},{"name":"attrData","type":1000}]}},"address":1927,"endpoint":1,"linkquality":164,"groupID":null}'
2021-02-23 06:11:29.896  - debug: zigbee.0 (3198) zigbee-herdsman:controller:log 'zcl' data is from unknown device with address '1927', skipping...
2021-02-23 06:11:29.897  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1
2021-02-23 06:11:29.901  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver query aps data indication
2021-02-23 06:11:29.902  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 174
2021-02-23 06:11:29.904  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:frameParser DATA_INDICATION RESPONSE - seqNr. 173 srcAddr: 0x787 destAddr: 0x0 profile id: 0x104 cluster id: 0x405
2021-02-23 06:11:29.905  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:frameParser response payload: 24,58,10,0,0,33,241,14
2021-02-23 06:11:29.907  - debug: zigbee.0 (3198) zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":true,"reservedBits":0},"transactionSequenceNumber":58,"manufacturerCode":null,"commandIdentifier":10},"Payload":[{"attrId":0,"dataType":33,"attrData":3825}],"Command":{"ID":10,"name":"report","parameters":[{"name":"attrId","type":33},{"name":"dataType","type":32},{"name":"attrData","type":1000}]}},"address":1927,"endpoint":1,"linkquality":164,"groupID":null}'
2021-02-23 06:11:29.907  - debug: zigbee.0 (3198) zigbee-herdsman:controller:log 'zcl' data is from unknown device with address '1927', skipping...
2021-02-23 06:11:29.908  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1
2021-02-23 06:11:29.909  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver query aps data indication
2021-02-23 06:11:29.910  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 175
2021-02-23 06:11:29.921  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:frameParser DATA_INDICATION RESPONSE - seqNr. 174 srcAddr: 0x787 destAddr: 0x0 profile id: 0x104 cluster id: 0x403
2021-02-23 06:11:29.921  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:frameParser response payload: 24,59,10,0,0,41,255,3,20,0,40,255,16,0,41,255,39
2021-02-23 06:11:29.925  - debug: zigbee.0 (3198) zigbee-herdsman:controller:log Received 'zcl' data '{"frame":{"Header":{"frameControl":{"frameType":0,"manufacturerSpecific":false,"direction":1,"disableDefaultResponse":true,"reservedBits":0},"transactionSequenceNumber":59,"manufacturerCode":null,"commandIdentifier":10},"Payload":[{"attrId":0,"dataType":41,"attrData":1023},{"attrId":20,"dataType":40,"attrData":-1},{"attrId":16,"dataType":41,"attrData":10239}],"Command":{"ID":10,"name":"report","parameters":[{"name":"attrId","type":33},{"name":"dataType","type":32},{"name":"attrData","type":1000}]}},"address":1927,"endpoint":1,"linkquality":164,"groupID":null}'
2021-02-23 06:11:29.925  - debug: zigbee.0 (3198) zigbee-herdsman:controller:log 'zcl' data is from unknown device with address '1927', skipping...
2021-02-23 06:11:29.926  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
2021-02-23 06:11:34.991  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver send read device state from queue. seqNr: 176
2021-02-23 06:11:35.000  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:frameParser device state: 10100010
2021-02-23 06:11:35.001  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
2021-02-23 06:11:44.987  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver send read device state from queue. seqNr: 177
2021-02-23 06:11:44.997  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:frameParser device state: 10100010
2021-02-23 06:11:44.998  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
2021-02-23 06:11:54.991  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver send read device state from queue. seqNr: 178
2021-02-23 06:11:54.999  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:frameParser device state: 10100010
2021-02-23 06:11:55.000  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
2021-02-23 06:12:04.988  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver send read device state from queue. seqNr: 179
2021-02-23 06:12:04.996  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:frameParser device state: 10100010
2021-02-23 06:12:04.997  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
2021-02-23 06:12:05.109  - debug: zigbee.0 (3198) Non-pingable device 0xd0cf5efffe7b93a0 TRADFRI wireless dimmer was last seen '17871049.339' seconds ago.
2021-02-23 06:12:05.123  - debug: zigbee.0 (3198) Non-pingable device 0xec1bbdfffe9c3336 TRADFRI on/off switch was last seen '17519.453' seconds ago.
2021-02-23 06:12:05.130  - debug: zigbee.0 (3198) Non-pingable device 0xec1bbdfffea09292 TRADFRI on/off switch was last seen '47405.044' seconds ago.
2021-02-23 06:12:05.135  - debug: zigbee.0 (3198) Non-pingable device 0x90fd9ffffe08d5c6 TRADFRI remote control was last seen '1432462.028' seconds ago.
2021-02-23 06:12:05.146  - debug: zigbee.0 (3198) Non-pingable device 0x000d6f000f5e0d70 Motion Sensor-A was last seen '788354.279' seconds ago.
2021-02-23 06:12:05.154  - debug: zigbee.0 (3198) Non-pingable device 0x00158d0003416e98 ZBT-Remote-ALL-RGBW was last seen '4899449.606' seconds ago.
2021-02-23 06:12:05.181  - debug: zigbee.0 (3198) zigbee-herdsman:controller:endpoint Read 0x842e14fffe139290/1 haElectricalMeasurement(["rmsVoltage","rmsCurrent","activePower"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false})
2021-02-23 06:12:05.183  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:adapter zclFrame.payload:
2021-02-23 06:12:05.184  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:adapter [ { attrId: 1285 }, { attrId: 1288 }, { attrId: 1291 } ]
2021-02-23 06:12:05.186  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver DATA_REQUEST - destAddr: 0xbdc7 EP:1 SeqNr. 180 request id: 147
2021-02-23 06:12:05.210  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:frameParser DATA_REQUEST RESPONSE - request id: 147 status: 0
2021-02-23 06:12:05.211  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
2021-02-23 06:12:05.215  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10100110
2021-02-23 06:12:05.216  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 1 apsDataIndication: 0 configChanged: 0 apsRequestFreeSlots: 1
2021-02-23 06:12:05.218  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver query aps data confirm
2021-02-23 06:12:05.220  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:frameParser DEVICE_STATE changed: 10101110
2021-02-23 06:12:05.221  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 1 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1
2021-02-23 06:12:05.222  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver DATA_CONFIRM - sending data state request - SeqNr. 181
2021-02-23 06:12:05.224  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver query aps data confirm
2021-02-23 06:12:05.227  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver Timeout for aps request CMD: 0x4 seq: 163
2021-02-23 06:12:05.228  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver query aps data indication
2021-02-23 06:12:05.229  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver DATA_CONFIRM - sending data state request - SeqNr. 182
2021-02-23 06:12:05.237  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 183
2021-02-23 06:12:05.238  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:frameParser DATA_CONFIRM RESPONSE - destAddr: 0xbdc7 request id: 147 confirm status: 0
2021-02-23 06:12:05.239  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver networkstate: 2 apsDataConfirm: 0 apsDataIndication: 1 configChanged: 0 apsRequestFreeSlots: 1
2021-02-23 06:12:05.239  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:adapter sendZclFrameToEndpoint - message send with transSeq Nr.: 132
2021-02-23 06:12:05.239  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver query aps data indication
2021-02-23 06:12:05.242  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:driver DATA_INDICATION - sending read data request - SeqNr. 184
2021-02-23 06:12:05.244  - debug: zigbee.0 (3198) zigbee-herdsman:deconz:adapter sendZclFrameToEndpoint ERROR: [object Object]
2021-02-23 06:12:05.247  - error: zigbee.0 (3198) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-02-23 06:12:05.247  - error: zigbee.0 (3198) unhandled promise rejection: undefined```


and i will patch and wait for the next errors...

**Comment by asgothian** [comment] 2021-02-23 11:12
Frage: Was ist das für ein Device: 0x842e14fffe139290
Kannst du das Device für einen Test aus dem Zigbee Netz werfen ? (Abschalten reicht leider nicht). So wie es aussieht gibt es  Probleme beim Abfragen der elektrischen Verbrauchswerte von diesem Gerät.

A.

**Comment by quotschmacher** [comment] 2021-02-23 11:31
blitzwolf shp13 - recognized as https://www.zigbee2mqtt.io/devices/TS0121_plug.html

before i remove the device: where can i find deconzAdapter.ts on my system? only one i found was:
```pi@IoBrokerPi3:/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/deconz/adapter $ ls -l
insgesamt 124
-rw-r--r--+ 1 iobroker iobroker  3916 Okt 26  1985 deconzAdapter.d.ts
-rw-r--r--+ 1 iobroker iobroker  3559 Okt 26  1985 deconzAdapter.d.ts.map
-rw-r--r--+ 1 iobroker iobroker 53624 Okt 26  1985 deconzAdapter.js
-rw-r--r--+ 1 iobroker iobroker 41268 Okt 26  1985 deconzAdapter.js.map
-rw-r--r--+ 1 iobroker iobroker   107 Okt 26  1985 index.d.ts
-rw-r--r--+ 1 iobroker iobroker   199 Okt 26  1985 index.d.ts.map
-rw-r--r--+ 1 iobroker iobroker   447 Okt 26  1985 index.js
-rw-r--r--+ 1 iobroker iobroker   200 Okt 26  1985 index.js.map```

**Comment by asgothian** [comment] 2021-02-23 11:34
That seems to be the correct one. Unfortunately i am not sure if you need to patch the deconzAdatper.d.ts oder deconzAdapter.js. I can check that later tonight when i am home. I have no access to my system right now.

The line to patch is in the function sendZclFrameToEndpoint.

A.

**Comment by quotschmacher** [comment] 2021-02-23 20:06
the hidden info was a status that is 5...you know better than me what it means. i will now delete the blitzwolf plug and report tomorrow if there are more errors or not.

```2021-02-23 20:20:46.947  - debug: zigbee.0 (6642) zigbee-herdsman:deconz:adapter sendZclFrameToEndpoint ERROR: {"status":5}
2021-02-23 20:20:46.950  - error: zigbee.0 (6642) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().```

**Comment by asgothian** [comment] 2021-02-25 10:45
Any updates if the error is linked to the Blitzwolf Plug or not ?

A

**Comment by quotschmacher** [comment] 2021-02-25 12:54
no updates - means no mor errors. but saying "you can't use this device with a conbee is not the solution i think. can i give you any more support for finding the error reason?

**Comment by asgothian** [comment] 2021-02-25 14:59
I am trying to identify the cause, which is tricky as i do not have one of those devices, and also do not have a conbee stick. It will take a bit more time to completely fix this as the final change will most likely have to be made in either zigbee-herdsman-converters or zigbee-herdsman, but an issue or PR on their site has little change without a more in depth error analysis.

I agree that not using the Blitzwolf plugs is not the desired solution.

A.

**Comment by quotschmacher** [comment] 2021-02-26 07:23
if you need me to add something to my code for testing or borrow you a conbee2 and blitwolf just tell me

**Comment by asgothian** [comment] 2021-02-26 12:47
Thank you for the offer. 
I will prepare something tomorrow and will ask you to patch the zigbee-herdsman-converters in a specific file in order to attempt to eradicate said bug.

**Comment by asgothian** [comment] 2021-02-27 10:00
Please check which version of the zigbee-herdsman-converters you have installed. Same goes with zigbee-herdsman.

If you have duplicate versions installed, please remove both and then reinstall the zigbee adapter from Github (latest beta) to see if the error persists. I believe there has been a change in the herdsman which may fix your issue.

A.

**Comment by quotschmacher** [comment] 2021-02-28 22:54
i just set up a new raspbian lite with iobroker, zigbee adapter github version and conbee ii stick and connected the blitzwolf plug. i will monitor it tomorrow.

**Comment by asgothian** [comment] 2021-03-07 08:27
Any news ?

**Comment by quotschmacher** [comment] 2021-03-07 21:51
not till now. i had problems connecting the blitzwolf plug with the conbee. just changed the conbee ii to a raspbee ii and it connected on the first try. i will monitor it tomorrow.

**Comment by quotschmacher** [comment] 2021-03-08 08:03
running for 10 hours now without any error. i'm logging with debug and zigbee-herdsmann output. is there anything specific you need from the log?

**Comment by asgothian** [comment] 2021-03-08 08:42
This would indicate that one of the following is correct:
- The error was fixed in updates to the zigbee-herdsman / zigbee-herdsman-converters
- The error is linked to the exact zigbee setup you have on your main system with the raspbee II (firmware, routing, etc.)

As far as i remember you did receive these errors after roughly 20 minutes runtime

A.

**Comment by quotschmacher** [comment] 2021-03-08 13:42
i would say the first variant. do you need any specific log output or can this issue be closed?

**Comment by asgothian** [comment] 2021-03-08 13:47
I would say it can be closed. Not that i know which change finally fixed it - i dug a lot but didn't change any code.

Please feel free to reopen if the error reoccurs when using the plug in your main installation.

A.

**Closed by asgothian** 2021-03-08 13:47 UTC
