### ISSUE TITLE
Value greater than 254

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.zigbee#1162] opened 2021-07-23 15:11 UTC
Now it's 199 .. otherwise I would have made a screenshot .. maybe you have an idea anyway:

1.5.6 (1~)

<html><body>

zigbee.0 | 2021-07-23 15:55:17.551 | warn | State value to set for "zigbee.0.00158d0002ead66e.link_quality" has value "255" greater than max "254"
-- | -- | -- | --
zigbee.0 | 2021-07-23 15:55:17.551 | warn | State value to set for "zigbee.0.00158d0002ead66e.link_quality" has value "255" greater than max "254"

</body>
</html>

**Comment by asgothian** [comment] 2021-07-26 11:45
Duplicate of #1160, 1157, 1140, 1126

A fix is available on GitHub but cannot be pushed to latest due to Compatibility issues in an underlying library.

**Comment by daniel-lo** [comment] 2021-07-26 13:41
So wait for the next update to show up from beta repo?

**Comment by StefCGN** [comment] 2021-07-26 18:18
Hi,
i also have the same problem here.

Additionally i have in the Log:
State value to set for "zigbee.0.00xxxxx00678d6d1.no_motion" has to be type "number" but received type "string"

**Comment by asgothian** [comment] 2021-07-27 11:02
> Hi,
> i also have the same problem here.
> 
> Additionally i have in the Log:
> State value to set for "zigbee.0.00xxxxx00678d6d1.no_motion" has to be type "number" but received type "string"

What kind of Device is this ? Please post the tile for this device.

**Comment by asgothian** [comment] 2021-07-27 11:02
> So wait for the next update to show up from beta repo?

Correct.

**Comment by StefCGN** [comment] 2021-07-28 06:08
> 
> 
> > Hi,
> > i also have the same problem here.
> > Additionally i have in the Log:
> > State value to set for "zigbee.0.00xxxxx00678d6d1.no_motion" has to be type "number" but received type "string"
> 
> What kind of Device is this ? Please post the tile for this device.

This is the Xiaomi Aqara Motion Sensor.

**Comment by asgothian** [comment] 2021-07-28 08:48
> This is the Xiaomi Aqara Motion Sensor.

Please post the tile for this device. In case you are unsung 1.5.6 or newer - the Info tile with the exact device information. The description is not good enough.

**Comment by StefCGN** [comment] 2021-07-28 08:53
> 
> 
> > This is the Xiaomi Aqara Motion Sensor.
> 
> Please post the tile for this device. In case you are unsung 1.5.6 or newer - the Info tile with the exact device information. The description is not good enough.

If you mean the model?
This is recognized by Zigbee Adapter: RTCGQ11LM

**Comment by Apollon77** [comment] 2021-08-05 13:20
@asgothian how it looks for release? COntroller 3.3. is out

**Comment by asgothian** [comment] 2021-08-06 06:13
> @asgothian how it looks for release? COntroller 3.3. is out

@kirovilya is preparing 1.6.0 which will include a fixed state description so that the error should no longer appear.

People who still experience the issue can fix it in one of 2 ways:
Option 1:
- stop the zigbee adapter
- remove the link quality state
- start the adapter. The link quality state will be regenerated with correct limits (0, 255)

Option 2
- edit the common.max value in the raw state description to change it from 254 to 255.

**Comment by marlan99** [comment] 2021-08-06 07:03
i am on the actual version 1.5.6

just tried your suggestions but with both ways it changes the max value to 254 again

**Comment by Speedbreaker12** [comment] 2021-08-06 11:17
> 
> 
> i am on the actual version 1.5.6
> 
> just tried your suggestions but with both ways it changes the max value to 254 again

jepp same here! If you want to get rid of the error you can install my repository:
https://github.com/Speedbreaker12/ioBroker.zigbee

until there is an official fix.

**Comment by daniel-lo** [comment] 2021-08-06 11:19
@Speedbreaker12 maybe I misunderstand .. but wouldn't it be wiser to maintain the version that is listed as iobroker adapter and not deviate to other forks?

**Comment by Speedbreaker12** [comment] 2021-08-06 11:27
> 
> 
> @Speedbreaker12 maybe I misunderstand .. but wouldn't it be wiser to maintain the version that is listed as iobroker adapter and not deviate to other forks?

yes, of course! :) My fork is meant as a temporary workaround it just limits the value from 255 to 254 for people that can't stand errors in their logs, like me. :) I already made a pull request but I can understand that they don't want to merge a fork that limits the value.

**Comment by StefCGN** [comment] 2021-08-06 11:29
I did it exactly like mentioned:
- Stop the Adapter
- delete EVERY state "link_quality" for EVERY Device
- restart the Adapter

Everything works ;)

Thanks!

**Comment by Speedbreaker12** [comment] 2021-08-06 11:32
> 
> 
> I did it exactly like mentioned:
> 
>     * Stop the Adapter
> 
>     * delete EVERY state "link_quality" for EVERY Device
> 
>     * restart the Adapter
> 
> 
> Everything works ;)
> 
> Thanks!

But it shouldn't at this point! :D You probably just don't have any values over 254!

**Comment by StefCGN** [comment] 2021-08-06 11:36
> 
> 
> > I did it exactly like mentioned:
> > ```
> > * Stop the Adapter
> > 
> > * delete EVERY state "link_quality" for EVERY Device
> > 
> > * restart the Adapter
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Everything works ;)
> > Thanks!
> 
> But it shouldn't at this point! :D You probably just don't have any values over 254!

False! If you delete the objects, the Adapter re-creates them and this with the correct way of:
`
  "type": "state",
  "common": {
    "name": "Link quality",
    "type": "number",
    "read": true,
    "write": false,
    "role": "state",
    "min": 0,
    "max": **255**
  }`

**Comment by Speedbreaker12** [comment] 2021-08-06 11:49
> 
> 
> > > I did it exactly like mentioned:
> > > ```
> > > * Stop the Adapter
> > > 
> > > * delete EVERY state "link_quality" for EVERY Device
> > > 
> > > * restart the Adapter
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Everything works ;)
> > > Thanks!
> > 
> > 
> > But it shouldn't at this point! :D You probably just don't have any values over 254!
> 
> False! If you delete the objects, the Adapter re-creates them and this with the correct way of:
> ` "type": "state", "common": { "name": "Link quality", "type": "number", "read": true, "write": false, "role": "state", "min": 0, "max": **255** }`

Only if you are on the git version, not on 1.5.6

**Comment by asgothian** [comment] 2021-08-06 14:52
Note that the fix is valid only for
- people who install the upcoming 1.6.0 version
- people who have installed the current GitHub version.


A.

**Comment by daniel-lo** [comment] 2021-08-10 05:56
deleted all objects and restarted 1.6.0 .. if I understood well I should be fine now :-)

**Comment by arteck** [comment] 2021-09-01 08:20
fixed

**Closed by arteck** 2021-09-01 08:20 UTC
Labels: duplicate
