### ISSUE TITLE
Zigbee clogs system

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.zigbee#1210] opened 2021-09-12 11:45 UTC
Hi, I'm having huge messages with my ioBroker not being accessible .. the only thing I notice on those occurances is extremely high cpu load .. esp. with the Zigbee adapter. I tried to stop zigbee from terminal when it happened but the database was blocked too .. so the command was rejected. I wonder why nobody else reports this .. is there any switch I could toggle to prevent this?

![grafik](https://user-images.githubusercontent.com/4311558/132986228-a1320d69-48d4-4af6-b74a-2180cac2cc90.png)

When the system is accessible zigbee load is clearly below 10%.

**Comment by asgothian** [comment] 2021-09-13 06:06
- Posting screenshots rather than log texts is bad style
- The fact that no-one is reporting this could be caused by the fact that it is not a common occurrance. In fact - i have not seen this before at all.
- Check your usage of the zigbee adapter, also check the logs for what the zigbee adapter is doing. (run the adapter in debug mode with zigbee-herdsman-debug info enabled and compare log activity from cases where the issue occurs and cases where it does not.
A.

**Comment by daniel-lo** [comment] 2021-09-15 14:32
This look strange to me .. one entry .. with double information:

![grafik](https://user-images.githubusercontent.com/4311558/133453207-fb89965c-99c1-418a-8609-20c81c4f09c2.png)

**Comment by asgothian** [comment] 2021-09-15 21:03
That looks normal.

check the log file for errors. If there are frequent restarts something is starting and stopping the adapter.

**Comment by daniel-lo** [comment] 2021-09-16 03:39
I'm just a guy trying to help (me and the community) .. I am not a programmer. So if my report is not interesting/helpful please mark it as resolved.

**Comment by asgothian** [comment] 2021-09-16 07:15
Your comment is helpful, but it is a lot of work to dig through 13 MB of logs to look for "something odd". If you have errors, you should locate those in the log and post the errors, not the entire log. Most error scenarios include rather clear statements as to what the issue is.

I can understand if you are no programmer, but reading logs has a lot to do with logic, and very little with programming.

**Comment by daniel-lo** [comment] 2021-09-16 07:25
My assumption is that devs have log reades with super filter possibilites .. I use a simple text editor .. which is probably not a good idea?!

**Comment by asgothian** [comment] 2021-09-16 10:20
Interesting assumption.

I would assume it is wrong for the most part, though. It is for me. I use a text editor for my log digging. An intelligent one, but still a text editor.

**Comment by daniel-lo** [comment] 2021-09-16 16:57
I see a huge amount of "DB closed" errors.

**Comment by asgothian** [comment] 2021-09-17 08:51
Triggered by which process ?

**Comment by daniel-lo** [comment] 2021-09-17 08:55
Redis?

![grafik](https://user-images.githubusercontent.com/4311558/133754728-ddc9f313-f2e3-4808-83a2-30a6936d8785.png)

**Comment by daniel-lo** [comment] 2021-09-17 08:57
2021-08-30 11:39:34.170  - [33mwarn[39m: zigbee.0 (12159) redis get zigbee.0.00158d0002ead66e.occupancy_timeout, error - Connection is closed.

2021-08-30 11:40:14.961  - [33mwarn[39m: zigbee.0 (12159) get state error: Connection is closed.


2021-08-30 11:50:17.055  - [33mwarn[39m: zigbee.0 (11549) get state error: Connection is closed.

2021-08-30 11:50:39.784  - [33mwarn[39m: zigbee.0 (11549) redis get zigbee.0.00158d0002ead66e.occupancy_timeout, error - Connection is closed.

2021-08-30 11:50:48.304  - [33mwarn[39m: zigbee.0 (11549) Could not perform strict object check of state zigbee.0.00158d0002ead66e.occupancy_timeout: Connection is closed.
2021-08-30 11:50:48.305  - [33mwarn[39m: zigbee.0 (11549) get state error: Connection is closed.

**Comment by asgothian** [comment] 2021-09-17 08:58
You seem to have an issue with access to your redis database, which you are using as storage for your states - this means that something is WAY off in your iobroker installation. The fact that the zigbee adapter is the one you see this from is caused by the fact that it is the one most often accessing the states.

A.

**Comment by daniel-lo** [comment] 2021-09-17 09:00
Amazing that it works most of the time :-(

Any idea how I can handle/fix this .. a pointer would be nice before I start to google in the wild.

**Comment by daniel-lo** [comment] 2021-09-17 09:07
Hmm .. I wonder .. should I have a redis-server on my machine?

daniel@iobroker:~$ redis-server --test-memory
Command 'redis-server' not found, but can be installed with:

**Comment by asgothian** [comment] 2021-09-17 09:44
I would suggest to take this issue to the iobroker forum. My experience with these kinds of issues is limited.

A.

**Comment by daniel-lo** [comment] 2021-09-17 10:17
As far as I understood Redis is a Custom thing for ioBroker .. so I really wonder why zigbee accesses Redis .. when it's not there.
And obviously it only does this sometimes .. since most of the time it works.

I can ask the forum.

**Comment by asgothian** [comment] 2021-09-20 15:52
Not a zigbee issue - closing

**Closed by asgothian** 2021-09-20 15:52 UTC

**Comment by daniel-lo** [comment] 2021-09-20 17:32
I wonder .. if the zigbee adapter wants to use a non-existing Redis DB .. it's not an adapter issue?

**Comment by asgothian** [comment] 2021-09-20 21:02
The zigbee adapter does not communicate directly with the objects do. This is done via the JS-controller, who also generates the message. The zigbee adapter just logs it.

this is no zigbee adapter issue.

**Comment by Apollon77** [comment] 2021-09-21 06:58
@asgothian This error means normally that the adapter tries to access the database after the "Unload" callback was called, so make sure that anything is cleaned up correctly in "Unload" and the callback only called after that! (e.g. serial connections when closed could still emit some data until the close callbacki scalled, so checl such stuff in unload

**Comment by Apollon77** [comment] 2021-09-21 07:00
PS: maximum default timeout for unload callback are 500ms! So cleanup can take lomger you can increase that timeout in io-package.json

**Comment by daniel-lo** [comment] 2021-09-21 07:18
@Apollon77 

"This error means normally that the adapter tries to access the database" .. thanks getting involved .. I am still confused though .. why would it access a database that doesn't exist? Or does iobroker carry it's own redis .. independent of redis being installed?!?

**Comment by asgothian** [comment] 2021-10-05 06:20
> @asgothian This error means normally that the adapter tries to access the database after the "Unload" callback was called, so make sure that anything is cleaned up correctly in "Unload" and the callback only called after that! (e.g. serial connections when closed could still emit some data until the close callbacki scalled, so checl such stuff in unload

@Apollon77 Question to that - the "Unload" when exactly is the "Unload" triggered and what is its function ? I have seen another mention of this issue and would like to understand the mechanics of this and how to change the zigbee adapter for this to no longer be an issue.
