### ISSUE TITLE
admin-tab is not loading with admin 5.0.24 (react activated)

### ISSUE THREAD

**Issue by sbormann** [ioBroker/ioBroker.zigbee#1100] opened 2021-05-14 22:44 UTC
![image](https://user-images.githubusercontent.com/49171332/118338536-b1b0e400-b516-11eb-8ec5-46b6b5395d8f.png)

**Comment by MMeinhardt1** [comment] 2021-05-15 13:37
Hi, siehe [hier](https://github.com/ioBroker/ioBroker.admin/issues/880)

**Comment by asgothian** [comment] 2021-05-17 07:16
Duplicate of #1098

**Comment by asgothian** [comment] 2021-05-31 10:48
Closed - seems fixed in newer Admin5 Versions.

**Closed by asgothian** 2021-05-31 10:48 UTC
Labels: duplicate
