### ISSUE TITLE
new device not supported: TS0601 from _TZE200_9xfjixap

### ISSUE THREAD

**Issue by akcsachsen** [ioBroker/ioBroker.zigbee#2275] opened 2024-11-02 12:21 UTC
hello,
I use the lastest iobroker 7.1.5. and the latest zigbee adapter 1.10.3
Node.js: v20.18.0
NPM: 10.8.2

now I got new devices, and they were found. but the iobroker told me: not supported:

Pairing time left: 43
Pairing time left: 44
Interview successful: {"friendly_name":"0xa4c13861bcadd1e8","supported":false}
Interview successful: {"friendly_name":"0xa4c13861bcadd1e8","supported":false}
Pairing time left: 45
New device joined '0xa4c13861bcadd1e8' model TS0601
New device joined '0xa4c13861bcadd1e8' model TS0601
Device '0xa4c13861bcadd1e8' announced itself
Device '0xa4c13861bcadd1e8' announced itself
Pairing time left: 46
Interview started: 0xa4c13861bcadd1e8
Interview started: 0xa4c13861bcadd1e8
Pairing time left: 47

a new device is found, but with no picture and no detail information:

modelZigbee:TS0601
type:EndDevice
nwk:7488
manuf id:4417
manufacturer:_TZE200_9xfjixap
power:Battery
app version:67
hard version:1
zcl version:3
stack version:0
date code:
interviewed:false
configured:false

in the log in only can find:
Device 0xa4c13861bcadd1e8 "TS0601" not described in statesMapping.

reboot / rejoin, everything I already tried, without success.

can you please help me ?

**Comment by akcsachsen** [comment] 2024-11-02 14:14
fyi:
I just updated to 1.10.11, but sadly this is not fixing the problem

**Comment by asgothian** [comment] 2024-11-02 19:22
Duplicate of #2252

**Closed by asgothian** 2024-11-02 19:22 UTC
