### ISSUE TITLE
Problem with Group and Color Temp #1390

### ISSUE THREAD

**Issue by UweLoyal** [ioBroker/ioBroker.zigbee#1391] opened 2022-03-06 09:27 UTC
Is it possible to fix that Problem?
The adapter ist part of ioBroker and if ioBroker can communicate with Lidl Lam, so it must work!
When I remember back, I didn't see error messages, I think they suddenly came up.
What I know, the Slider of Group (ct) worked at the beginning, now he doesn't!
The slider in Group is moveable, but has no effect to the lamp sliders.
The funny thing is, ct of Lidl lamp changes with moving slider of group in reality!

_Originally posted by @UweLoyal in https://github.com/ioBroker/ioBroker.zigbee/issues/1390#issuecomment-1059842574_

**Comment by asgothian** [comment] 2022-03-06 12:52
Duplicate of #1390.
Answered in #1390

**Closed by asgothian** 2022-03-06 12:52 UTC
Labels: duplicate, wontfix, Intended behavior
