### ISSUE TITLE
Aqara WXKG12LM

### ISSUE THREAD

**Issue by Shepherd7** [ioBroker/ioBroker.zigbee#1222] opened 2021-09-26 11:18 UTC
Aqara WXKG12LM wireless button

change state, true/false, only work in Long Click.
click and double click not working true/false

ioboker Proxmox VM ubuntu 20.04 LTS
NODE.JS: V12.22.6
js controller 3.3.18
npm 6.14.15

Zigbee Adapter 1.6.0
TI CC1352P-2

**Comment by asgothian** [comment] 2021-09-27 06:02
Duplicate of #1218 

Please perform the test suggested there and post the respective log messages, with the data to be entered into the debugmessages state being the ieee Address of the affected button.

A.

**Closed** 2022-01-14 10:58 UTC
Labels: duplicate
