### ISSUE TITLE
Adapter not starting after 1.5.5 update

### ISSUE THREAD

**Issue by 1N4148** [ioBroker/ioBroker.zigbee#1105] opened 2021-05-20 19:46 UTC
Updated the adapter to npm 1.5.5 and now I'm getting these errors and the adapter won't start

`

zigbee.0 | 2021-05-20 21:44:17.590 | error | (420) Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port' at Znp.&lt;anonymous&gt; (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herd
-- | -- | -- | --
zigbee.0 | 2021-05-20 21:44:17.587 | error | (420) Failed to start Zigbee
zigbee.0 | 2021-05-20 21:44:17.129 | info | (420) Installed Version: asgothian/ioBroker.zigbee#RawState
zigbee.0 | 2021-05-20 21:44:17.071 | info | (420) Starting Zigbee npm ...
zigbee.0 | 2021-05-20 21:44:17.067 | info | (420) Try to reconnect. 1 attempts left
zigbee.0 | 2021-05-20 21:44:07.063 | error | (420) TypeError: Cannot read property 'warn' of undefined at ZnpAdapterManager.&lt;anonymous&gt; (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/man
zigbee.0 | 2021-05-20 21:44:07.060 | error | (420) Failed to start Zigbee
zigbee.0 | 2021-05-20 21:44:05.287 | info | (420) Installed Version: asgothian/ioBroker.zigbee#RawState
zigbee.0 | 2021-05-20 21:43:12.403 | info | (420) Starting Zigbee npm ...
zigbee.0 | 2021-05-20 21:43:11.963 | info | (420) starting. Version 1.5.5 in /opt/iobroker/node_modules/iobroker.zigbee, node: v14.17.0, js-controller: 3.2.16

`

**Comment by Apollon77** [comment] 2021-05-20 20:40
"Cannot lock port" normally means that the serial port is blocked by another process, please check that first

**Comment by 1N4148** [comment] 2021-05-20 20:45
That was the first thing I've checked. Also rebooted, disconnected & reconnected CC-Stick.

**Comment by 1N4148** [comment] 2021-05-20 21:31
Looks like there's something damaged in the configs. If I start with a clean adapter, it works. As soon as I restore a backup I'm getting the above errors. Regardless whether the stick is plugged in directly or over a ser2net connection.

**Comment by kirovilya** [comment] 2021-05-21 04:11
hmm. the main error is not with the port, but

> (420) TypeError: Cannot read property 'warn' of undefined at ZnpAdapterManager.<anonymous> (/opt/iobroker/node_modules/iobroker.zigbee/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/man

I'll see what i can do

**Comment by asgothian** [comment] 2021-05-21 05:58
Please update from my defunct “raw state” test branch to the official 1.5.5 and then check again.

A.

**Comment by Shadesh** [comment] 2021-05-21 06:05
https://github.com/ioBroker/ioBroker.zigbee/issues/1091 Se my second comment, same error.

**Comment by kirovilya** [comment] 2021-05-21 08:50
try to update adapter from github now

**Comment by Shadesh** [comment] 2021-05-21 09:27
`

zigbee.0 | 2021-05-21 11:27:26.740 | error | (14060) Error: Error while opening serialport 'Error: Error Resource temporarily unavailable Cannot lock port' at Znp.&lt;anonymous&gt; (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-stack/z
-- | -- | -- | --
zigbee.0 | 2021-05-21 11:27:26.739 | error | (14060) Failed to start Zigbee
zigbee.0 | 2021-05-21 11:27:26.547 | info | (14060) Installed Version: ioBroker/ioBroker.zigbee#master
zigbee.0 | 2021-05-21 11:27:26.504 | info | (14060) Starting Zigbee npm ...
zigbee.0 | 2021-05-21 11:27:26.503 | info | (14060) Try to reconnect. 1 attempts left
zigbee.0 | 2021-05-21 11:27:16.503 | error | (14060) Error: startup failed - configuration-adapter mismatch - see logs above for more information at ZnpAdapterManager.&lt;anonymous&gt; (/opt/iobroker/node_modules/zigbee-herdsman/dist/adapter/z-sta
zigbee.0 | 2021-05-21 11:27:16.502 | error | (14060) Failed to start Zigbee
zigbee.0 | 2021-05-21 11:27:16.501 | error | (14060) Re-commissioning your network will require re-pairing of all devices!
zigbee.0 | 2021-05-21 11:27:16.501 | error | (14060) If you wish to re-commission your network, please remove coordinator backup at /opt/iobroker/iobroker-data/zigbee_0/nvbackup.json.
zigbee.0 | 2021-05-21 11:27:16.500 | error | (14060) Please update configuration to prevent further issues.
zigbee.0 | 2021-05-21 11:27:16.500 | error | (14060) - Channel List: configured=11, adapter=11
zigbee.0 | 2021-05-21 11:27:16.500 | error | (14060) - Network Key: configured=9852964ea62c474a18b1b23a1f055338, adapter=9852964ea62c474a18b1b23a1f055338
zigbee.0 | 2021-05-21 11:27:16.499 | error | (14060) - Extended PAN ID: configured=d4b1cf2ffc88da8d, adapter=00124b0008c9889a
zigbee.0 | 2021-05-21 11:27:16.498 | error | (14060) - PAN ID: configured=6754, adapter=6754
zigbee.0 | 2021-05-21 11:27:16.498 | error | (14060) Configuration is not consistent with adapter state/backup!

`

**Comment by kirovilya** [comment] 2021-05-21 09:57
@Shadesh very strange...

**Comment by Shadesh** [comment] 2021-05-21 09:59
Exactly what I thought ;) - As soon as I revert to my "backup" 1.5.3 from GitHub, the adapter starts up again.

**Comment by kirovilya** [comment] 2021-05-21 10:01
perhaps there was no such check before, but now it has appeared and is blocking the start

**Comment by kirovilya** [comment] 2021-05-21 11:35
Let's clarify. You now have extpanid = d4b1cf2ffc88da8d in the adapter settings. This is true?
If so, you can try to set in the adapter settings the extPanID indicated by the error = 00124b0008c9889a
But I'm not sure what will happen ... these checks were added recently when changing the backup work in zigbee-herdsman

**Comment by Shadesh** [comment] 2021-05-21 11:43
Well unfortunately both ID's does't match the set ID. 
The current set extended Pan ID is completely different from what the log said.
From my understanding the ext. ID is saved in the file "/opt/iobroker/iobroker-data/zigbee_0/nvbackup.json"?
If so, where does the adapter get this completely different ID's from? Just to understand the process here.

**Comment by kirovilya** [comment] 2021-05-21 12:09
yes is reversed when used (do not know why) :)
so can reverse 00124b0008c9889a to 9a88c908004b1200

**Comment by 1N4148** [comment] 2021-05-22 10:02
Partially repaired my network by installing github version, rolling back to a older backup of zigbee database and did the PAN ID trick (changing PAN ID forth and back)

But somehow some of the devices won't work anymore. If they are paired to the adapter they show up as Available but aren't sending data (e.g. SNZB02 temperature sensors). Pairing them to another adapter they are working.

**Comment by vaaarg** [comment] 2021-05-23 05:46
had the same problem. completely trashed my zigbee network. Rollback also failed. 

CC26X2R1

**Comment by castorw** [comment] 2021-05-25 11:28
Some attributes were improperly configured by previous ZH code-base. The main problem was the EPID (your case), which was set to 0xdddddddddddddddd or reversed. These cases are taken care of and ignored or let off with a warning. However according to this:
```
2021-05-21 11:27:16.499  - error: zigbee.0 (14060) - Extended PAN ID: configured=d4b1cf2ffc88da8d, adapter=00124b0008c9889a
```

The EPID is completely different. To overcome this issue you can either adapt your configuration to respect the EPID configured by adapter (which seems like its IEEE address) or use the default (0xdddddddddddddddd) as configured value.

**Comment by Shadesh** [comment] 2021-05-25 11:32
Sooo, change the extPANID to 00124b0008c9889a in IOBroker Zigbee Config. My question here, is it safe to reconfigure the extPANID? It's **absolutely no fun** to reconfigure nearly 60 Zigbee devices...

**Comment by castorw** [comment] 2021-05-25 11:41
@Shadesh I don't see under the hood fo ioBroker (dunno how it handles configuration changes), however speaking of ZH -  if you update the configuration to match the EPID reported by ZH it should start properly.

**Comment by arteck** [comment] 2021-05-25 17:38
check plz plz now with this version from GIT

**Comment by Shadesh** [comment] 2021-05-26 06:35
@arteck So the conclusion is: Change the EPID to the **not** manual configured one, delete nvbackup.json and restart zigbee adapter? I'm a bit confused ;)

**Comment by arteck** [comment] 2021-05-26 08:18
I know it is confusing.. but yes... this is the trick...

or you can use the DDDDDDDDDDDDDDDD ..

**Comment by Shadesh** [comment] 2021-05-26 08:26
Do i have to reconfigure / re-pair my Zigbee devices after that change? I'm asking, because that's what the error message in your screenshoot say's when deleting the nvbackup.js file.

**Comment by arteck** [comment] 2021-05-26 09:33
Do i have to reconfigure / re-pair my Zigbee devices after that change?  : YES

**Comment by Shadesh** [comment] 2021-05-26 09:46
Thanks. Then I'm staying with 1.5.3 for now.

**Comment by asgothian** [comment] 2021-05-27 10:51
There is one additional option:
- Update to 1.5.5
- Catch the error message, and check which ext-Pan ID is listed as "configured" for your network
- Update the ext-Pan ID entered in the Adapter to the "reversed" Entry of what is listed as "configured" by the message.
- Restart the adapter.

Note: Reverse in this case is not just all chars in reverse order, but all "bytes" in reverse order, so
`00124b0008c9889a` would reverse to `9a88c908004b1200` 

This should remove the issue for you and allow for you to update to newer versions later without any issues and without having to re-pair all your devices.

If you make a backup of your nvbackup.json and shepherd.db files **and** note down the current ExtPanID of your config this can be undone by going back to 1.5.3, restoring both files and the ExtPanID you wrote down.

A.

**Comment by Shadesh** [comment] 2021-05-27 15:43
Do I miss something here? Looks like this doesn't work:
First start with old EPANID, second with the reversed.

```
2021-05-27 17:38:49.878  - info: zigbee.0 (15045) starting. Version 1.5.6 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.22.1, js-controller: 3.2.
16
2021-05-27 17:38:49.998  - info: zigbee.0 (15045) Starting Zigbee  npm ...
2021-05-27 17:38:50.335  - info: zigbee.0 (15045) Installed Version: ioBroker/ioBroker.zigbee#master
2021-05-27 17:38:52.021  - error: zigbee.0 (15045) Configuration is not consistent with adapter state/backup!
2021-05-27 17:38:52.022  - error: zigbee.0 (15045) - PAN ID: configured=6754, adapter=6754
2021-05-27 17:38:52.023  - error: zigbee.0 (15045) - Extended PAN ID: configured=d4b1cf2ffc88da8d, adapter=00124b0008c9889a
2021-05-27 17:38:52.024  - error: zigbee.0 (15045) - Network Key: configured=<removed>, adapter=<removed>
2021-05-27 17:38:52.025  - error: zigbee.0 (15045) - Channel List: configured=11, adapter=11
2021-05-27 17:38:52.026  - error: zigbee.0 (15045) Please update configuration to prevent further issues.
2021-05-27 17:38:52.027  - error: zigbee.0 (15045) If you wish to re-commission your network, please remove coordinator backup at /opt/iobroker/iobroker-dat
a/zigbee_0/nvbackup.json.
2021-05-27 17:38:52.028  - error: zigbee.0 (15045) Re-commissioning your network will require re-pairing of all devices!
2021-05-27 17:38:52.030  - error: zigbee.0 (15045) Starting zigbee-herdsman problem : "startup failed - configuration-adapter mismatch - see logs above for 
more information"
2021-05-27 17:38:52.032  - error: zigbee.0 (15045) Failed to start Zigbee
2021-05-27 17:38:52.033  - error: zigbee.0 (15045) Error herdsman start
2021-05-27 17:39:02.035  - info: zigbee.0 (15045) Try to reconnect. 1 attempts left
2021-05-27 17:39:02.037  - info: zigbee.0 (15045) Starting Zigbee  npm ...
2021-05-27 17:39:02.078  - info: zigbee.0 (15045) Installed Version: ioBroker/ioBroker.zigbee#master
2021-05-27 17:39:02.270  - error: zigbee.0 (15045) Starting zigbee-herdsman problem : "Error while opening serialport 'Error: Error Resource temporarily una
vailable Cannot lock port'"
2021-05-27 17:39:02.270  - error: zigbee.0 (15045) Failed to start Zigbee
2021-05-27 17:39:02.271  - error: zigbee.0 (15045) Error herdsman start
2021-05-27 17:39:11.252  - info: zigbee.0 (15045) Got terminate signal TERMINATE_YOURSELF
2021-05-27 17:39:11.253  - info: zigbee.0 (15045) cleaned everything up...
2021-05-27 17:39:11.257  - info: zigbee.0 (15045) Zigbee: disabling joining new devices.
2021-05-27 17:39:11.259  - warn: zigbee.0 (15045) Failed to stop zigbee during startup
2021-05-27 17:39:11.260  - info: zigbee.0 (15045) terminating
2021-05-27 17:39:11.261  - info: zigbee.0 (15045) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
2021-05-27 17:39:11.262  - error: zigbee.0 (15045) Unhandled promise rejection. This error originated either by throwing inside of an async function without
 a catch block, or by rejecting a promise which was not handled with .catch().
2021-05-27 17:39:11.263  - error: zigbee.0 (15045) unhandled promise rejection: Cannot read property 'getEntries' of null
2021-05-27 17:39:11.264  - error: zigbee.0 (15045) TypeError: Cannot read property 'getEntries' of null
    at Function.loadFromDatabaseIfNecessary (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/device.js:220:55)
    at Function.all (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/model/device.js:240:16)
    at Controller.getDevices (/opt/iobroker/node_modules/zigbee-herdsman/dist/controller/controller.js:303:31)
    at ZigbeeController.getClients (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:228:49)
    at DeviceAvailability.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceAvailability.js:222:43)
    at ZigbeeController.callExtensionMethod (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:214:42)
    at ZigbeeController.stop (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:385:20)
    at Zigbee.onUnload (/opt/iobroker/node_modules/iobroker.zigbee/main.js:696:41)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-05-27 17:39:11.265  - error: zigbee.0 (15045) Cannot read property 'getEntries' of null



2021-05-27 17:39:46.684  - info: sql.0 (1519) enabled logging of zigbee.0.info.connection, Alias=false
2021-05-27 17:39:46.706  - info: sql.0 (1519) enabled logging of zigbee.0.info.pairingMessage, Alias=false
2021-05-27 17:39:46.756  - info: zigbee.0 (15111) starting. Version 1.5.6 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.22.1, js-controller: 3.2.
16
2021-05-27 17:39:46.893  - info: zigbee.0 (15111) Starting Zigbee  npm ...
2021-05-27 17:39:47.250  - info: zigbee.0 (15111) Installed Version: ioBroker/ioBroker.zigbee#master
2021-05-27 17:39:48.880  - error: zigbee.0 (15111) Configuration is not consistent with adapter state/backup!
2021-05-27 17:39:48.880  - error: zigbee.0 (15111) - PAN ID: configured=6754, adapter=6754
2021-05-27 17:39:48.881  - error: zigbee.0 (15111) - Extended PAN ID: configured=8dda88fc2fcfb1d4, adapter=00124b0008c9889a
2021-05-27 17:39:48.882  - error: zigbee.0 (15111) - Network Key: configured=<removed>, adapter=<removed>
2021-05-27 17:39:48.882  - error: zigbee.0 (15111) - Channel List: configured=11, adapter=11
2021-05-27 17:39:48.882  - error: zigbee.0 (15111) Please update configuration to prevent further issues.
2021-05-27 17:39:48.883  - error: zigbee.0 (15111) If you wish to re-commission your network, please remove coordinator backup at /opt/iobroker/iobroker-dat
a/zigbee_0/nvbackup.json.
2021-05-27 17:39:48.883  - error: zigbee.0 (15111) Re-commissioning your network will require re-pairing of all devices!
2021-05-27 17:39:48.884  - error: zigbee.0 (15111) Starting zigbee-herdsman problem : "startup failed - configuration-adapter mismatch - see logs above for 
more information"
2021-05-27 17:39:48.885  - error: zigbee.0 (15111) Failed to start Zigbee
2021-05-27 17:39:48.885  - error: zigbee.0 (15111) Error herdsman start
2021-05-27 17:39:58.886  - info: zigbee.0 (15111) Try to reconnect. 1 attempts left
2021-05-27 17:39:58.888  - info: zigbee.0 (15111) Starting Zigbee  npm ...
2021-05-27 17:39:58.931  - info: zigbee.0 (15111) Installed Version: ioBroker/ioBroker.zigbee#master
2021-05-27 17:39:59.136  - error: zigbee.0 (15111) Starting zigbee-herdsman problem : "Error while opening serialport 'Error: Error Resource temporarily una
vailable Cannot lock port'"
2021-05-27 17:39:59.136  - error: zigbee.0 (15111) Failed to start Zigbee
2021-05-27 17:39:59.137  - error: zigbee.0 (15111) Error herdsman start
```

**Comment by asgothian** [comment] 2021-05-28 06:05
> And let me ask: Why is this field from the Extended PAN ID editable at all? For me, it looks like this would lead to problems every time you change that to something random?! If there is a EPANID from the adapter itself, why not use that and make it non editable, even not visible?
> 
> Edit:
> I sniffed my Zigbee Network with Wireshark and got the real Extended PAN ID broadcasted to the Zigbee network, it's not the "configured" one but the one from the adapter itself. With this knowledge, the set EPANID in IOBroker is somehow useless from my sight of view...

When the adapter is initially installed, the ext-pan ID needs to be set by the adapter configuration. Without this, the herdsman would always use DDDDDDDDDDDDDDDD as extPanID, which can cause issues when running multiple instances.

The entire issue with reversed pan ID's is caused by a refactoring which was done in the Herdsman about 2 weeks ago. It seems (even though this cannot be certain at this point) that a bug in this refactoring caused the entry to be reversed at some point. The entire method of checking extPanId vs a stored extPanId is also a new addition in the Herdsman as a result of this refactoring.

Unfortunately, the text in the error messages may cause confusion when considering the iobroker.zigbee Adapter, as "configured" refers to the entries made in the iobroker.zigbee Adapter configuration, while "adapter" entry refer to the ExtPanID stored in the backup of the zigbee network configuration. This does match the result from your network sniffer.
This PanID was at one time set from the zigbee Adapter, and has been used since to safeguard your zigbee network. Why this does not match the entry you had in your configuration is very hard to determine at this point.

The ExtPanID from the configuration is transferred to the zigbee-herdsman in reversed byte order. For Compatibility, this has to remain as any change on this will cause similar issues to the one you had for people updating to 1.5.5, which adds to the confusion of the error message as the "configured" PanID will have a reverse byte order to what has been entered in the zigbee Admin. 

A.

**Comment by Shadesh** [comment] 2021-05-28 06:30
> This PanID was at one time set from the zigbee Adapter, and has been used since to safeguard your zigbee network. Why this does not match the entry you had in your configuration is very hard to determine at this point.

First, thanks for your explanation! Well, the IOBroker Zigbee Config Page tells you, to set this to a 16 character long random hex decimal. I did that at the very beginning of my Zigbee config with IOBroker long time ago because of

> Without this, the herdsman would always use DDDDDDDDDDDDDDDD as extPanID, which can cause issues when running multiple instances.

but, if the Extended PAN ID comes directly from the zigbee adapter itself, which seems to be true at least for my hardware, why is this field editable? I mean get the EPANID from the NVRAM from the zigbee device, store it and go on. We got a lot of "self made" hardware zigbee adapters this time and if the "manufacturer" of this stick, didn't change this EPANID for every stick this could lead to problems with multiple instances. (Never looked at the source code of the [most used](https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.0.x) firmware for it) But afaik the set EPANID in IOBroker isn't used at all nor is it saved to the nvram of the zigbee device.

**Comment by asgothian** [comment] 2021-05-28 07:03
> > This PanID was at one time set from the zigbee Adapter, and has been used since to safeguard your zigbee network. Why this does not match the entry you had in your configuration is very hard to determine at this point.
> 
> First, thanks for your explanation! Well, the IOBroker Zigbee Config Page tells you, to set this to a 16 character long random hex decimal. I did that at the very beginning of my Zigbee config with IOBroker long time ago because of
> 
> > Without this, the herdsman would always use DDDDDDDDDDDDDDDD as extPanID, which can cause issues when running multiple instances.
> 
> but, if the Extended PAN ID comes directly from the zigbee adapter itself, which seems to be true at least for my hardware, why is this field editable? I mean get the EPANID from the NVRAM from the zigbee device, store it and go on. We got a lot of "self made" hardware zigbee adapters this time and if the "manufacturer" of this stick, didn't change this EPANID for every stick this could lead to problems with multiple instances. (Never looked at the source code of the [most used](https://github.com/Koenkk/Z-Stack-firmware/tree/master/coordinator/Z-Stack_3.0.x) firmware for it) But afaik the set EPANID in IOBroker isn't used at all nor is it saved to the nvram of the zigbee device.


As far as i am aware of, the EPANID is not inherent in the zigbee devices but is generated when the zigbee Network is provisioned for the first time. I am not certain if the firmware for the coordinator contains an inherent EPANID, but i somehow doubt it.
The fact that you were able to sniff a EPANID from your zigbee network is caused by the fact that the network is a mesh network with NO mandatory nodes. As such, the network will remain active even if the zigbee coordinator goes offline (in your case: Zigbee Adapter is not running). This fact is used when binding devices to each other, and allows e.g. the control of ikea TradFri bulbs from Ikea Remotes without using any coordinator. 
During the pairing process, the zigbee device needs to record the EPANID and store it in its NVRAM to be able to communicate within the network.

A.

**Comment by Shadesh** [comment] 2021-05-28 07:15
Understood. From what I read, the EPANID is generated if all values are zero in initial operations of a coordinator hardware. If not zero, its already present (pre generated or whatever) with a random value or its fetched and saved from a process like the IOBroker Adapter: Set it one time, save it "forever".

So my suggestion here is: If this value is once known, fetch it and make the field in IOBroker non editable. I think this would lead to less confusion in future. I really have no idea, if I changed this value in past because of the change from a cc2531 to the current CC2538. If I did that, it would make sense why all this happened. And I'm sure im not the only one who (maybe) did that.

**Comment by asgothian** [comment] 2021-05-28 07:19
> So my suggestion here is: If this value is once known, fetch it and make the field in IOBroker non editable. I think this would lead to less confusion in future. I really have no idea, if I changed this value in past because of the change from a cc2531 to the current CC2538. If I did that, it would make sense why all this happened. And I'm sure im not the only one who (maybe) did that.

This is not a sensible option. The user should have the option to change the network parameters if desired. Else we could also do the same for **channel** and **PanID**, which, if changed on an existing network will currently generate a similar error message.

What is considered is to not throw the adapter in a startup loop but generate a message for the user offering one of 2 choices:
- undo the change and start with the existing parameters
- keep the changes and reprovision the network.
A.

**Comment by castorw** [comment] 2021-05-28 08:12
Let me break it down in several points:
* **Default EPID:** When you do not configure EPID, the default (0xdddddddddddddddd) is used. Depending on firmware this was either used literally or treated as default (aka. use adapter IEEE) by the adapter - causing some adapters to use literal default and others to use adapter's IEEE address. That's why I decided to use the adapters' IEEE address instead of the default.
* **Reversed EPID:** If you have configured the EPID manually, it was stored in straight byte order in the adapter (this was wrong, since the adapter internally reverses addresses and most data). This was incorrect implementation within ZH, so I decided to fix it and tried to find a way to inform the user but not to crash so - if the EPID is literal default (0xdddddddddddddddd) or reversed against configuration, ZH should start ignoring this sad fact.
* **Updating the network:** Previously you could have ran into problem pretty quickly by updating configuration and easily losing your network, the startup strategy SM and several protections are there to prevent such situations. Rather fail with a warning or error than to lose your network by making a small mistake. Updating the network in the means of **actually** updating the network without the need to re-pair devices is pretty complicated and may not even be possible on a lot of LE devices, so that's why you are basically unable to "change network parameters" without re-pairing devices.

**Comment by Shadesh** [comment] 2021-05-28 08:37
> * **Updating the network:** Previously you could have ran into problem pretty quickly by updating configuration and easily losing your network, the startup strategy SM and several protections are there to prevent such situations. Rather fail with a warning or error than to lose your network by making a small mistake. Updating the network in the means of **actually** updating the network without the need to re-pair devices is pretty complicated and may not even be possible on a lot of LE devices, so that's why you are basically unable to "change network parameters" without re-pairing devices.

I absolutely agree with you when you want to protect users from epic fails, by editing the config without warning or even error msg before the real bang occurs. 

I'm sure that i'm not the only one who made this kind of "mistake". So I would either suggest to change the current error msg in log to something more understandable. For me it wasn't clear that I can simply change the EPANID to the "Adapter" one without loosing all my devices, maybe this should be made clear enough in the message.

Or even more "zero touch":

Prefill the Extended PAN ID field in IOBroker Config Page with the one active and used at the moment. The set one was, at least in my case, somehow useless. It only produced the error msg. Maybe in combination with a warning log entry when updating the adapter from a version where it wasn't checked at all.

Just to prevent more silly issues like mine in future ;)

And for your latest comment: Of course, force changing channel and / or (E)PANID would lead to a re-paring scenario.

For me the situation is explained enough, I understood the issue and the reason for the current error in log.
So again, thanks everybody.

**Comment by asgothian** [comment] 2021-05-28 09:21
> Or even more "zero touch":
> 
> Prefill the Extended PAN ID field in IOBroker Config Page with the one active and used at the moment. The set one was, at least in my case, somehow useless. It only produced the error msg. Maybe in combination with a warning log entry when updating the adapter from a version where it wasn't checked at all.

I am not certain this is feasible, as i do not know if we can query this data before the zigbee-herdsman starts. This will need to be evaluated, even if only for a better error handling.

A.

**Closed** 2021-09-20 15:56 UTC
