### ISSUE TITLE
Problem with Philips bulb

### ISSUE THREAD

**Issue by hanwel** [ioBroker/ioBroker.zigbee#907] opened 2020-12-22 07:49 UTC
Hi, 

Device: Philips A60 Bulb Model 8718699673147
Adapter: 1.4.1
Coordinator: ti cc26x2r1 

my log shows every few minutes the following entries:

`2020-12-22 08:43:23.095 - error: zigbee.0 (19663) Error on send command to 0x0017880108be1a65. Error: Error: Command 0x0017880108be1a65/11 genOnOff.off({}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":false,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null}) failed (Timeout - 7412 - 11 - 60 - 6 - 11 after 10000ms)`

Any idea how to fix it?

Thanks, Hanno

**Comment by asgothian** [comment] 2020-12-22 09:22
Yes - improve your network stability.
The timeout occurs because the command cannot be sent to the Bulb or is not acknowledged by the Bulb. This is usually caused by
- the Bulb not actually having any power
- the wireless connection being bad due to dampening or interference

There is no software fix for this.

A.

**Comment by hanwel** [comment] 2020-12-22 15:34
Thanks, power and connectivity is fine, will check for interferences.

**Comment by asgothian** [comment] 2020-12-28 10:41
No additional information - assuming problem is fixed.

**Closed by asgothian** 2020-12-28 10:41 UTC
