### ISSUE TITLE
Crash with latest version from github

### ISSUE THREAD

**Issue by PastCoder** [ioBroker/ioBroker.zigbee#2235] opened 2024-10-14 16:58 UTC
Today I updated to the latest code in github. 
Since then the adapter starts, works as expected and crashs after a while:

2024-10-14 18:47:32.563 - info: zigbee.0 (96290) Zigbee started
2024-10-14 18:50:00.544 - error: zigbee.0 (96290) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-10-14 18:50:00.546 - error: zigbee.0 (96290) unhandled promise rejection: Cannot read properties of undefined (reading 'includes')
2024-10-14 18:50:00.548 - error: zigbee.0 (96290) TypeError: Cannot read properties of undefined (reading 'includes')
2024-10-14 18:50:00.548 - error: zigbee.0 (96290) Cannot read properties of undefined (reading 'includes')
2024-10-14 18:50:00.580 - info: zigbee.0 (96290) cleaned everything up...
2024-10-14 18:50:00.585 - info: zigbee.0 (96290) Zigbee: disabling joining new devices.
2024-10-14 18:50:01.085 - info: zigbee.0 (96290) terminating
2024-10-14 18:50:01.089 - warn: zigbee.0 (96290) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-10-14 18:50:01.179 - info: zigbee.0 (96290) terminating
2024-10-14 18:50:01.722 - error: host.mediapc instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

**Comment by asgothian** [comment] 2024-10-14 18:51
Duplicate of #2211

**Closed by asgothian** 2024-10-14 18:51 UTC
