### ISSUE TITLE
Fehlermeldung für die Zukunft beim anlernen TS011F

### ISSUE THREAD

**Issue by tugsi** [ioBroker/ioBroker.zigbee#1611] opened 2022-12-09 13:31 UTC
Wenn ich den TS011F anlerne, kommen folgende Fehlermeldungen:

 | warn | This object will not be created in future versions. Please report this to the developer.
-- | -- | --
 | warn | Object zigbee.0.a4c138cbdc824145.indicator_mode is invalid: obj.common.states has an invalid type! Expected "object", received "string"
 | warn | This object will not be created in future versions. Please report this to the developer.
 | warn | Object zigbee.0.a4c138cbdc824145.power_outage_memory is invalid: obj.common.states has an invalid type! Expected "object", received "string"
 | warn | This object will not be created in future versions. Please report this to the developer.
 | warn | Object a4c138cbdc824145.indicator_mode is invalid: obj.common.states has an invalid type! Expected "object", received "string"
 | warn | This object will not be created in future versions. Please report this to the developer.
 | warn | Object a4c138cbdc824145.power_outage_memory is invalid: obj.common.states has an invalid type! Expected "object", received "string"
 | info | Configuring 0xa4c138cbdc824145 TS011F
 | info | Device '0xa4c138cbdc824145' is supported, identified as: TuYa Smart plug (with power monitoring) (TS011F_plug_1)
 | info | Successfully interviewed '0xa4c138cbdc824145', device has successfully been paired
 | warn | Device '0xa4c138cbdc824145' announced itself
 | info | Starting interview of '0xa4c138cbdc824145'

**Comment by asgothian** [comment] 2022-12-09 14:26
Duplicate of #1602

**Closed by asgothian** 2022-12-09 14:26 UTC
Labels: duplicate
